"""empty message

Revision ID: 657750a6c947
Revises: 
Create Date: 2018-09-05 11:11:36.808524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657750a6c947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chore', 'completed')
    # ### end Alembic commands ###
